### PR TITLE
Implement responsive design

### LINKED ISSUE #48: Mobile responsiveness
- [x] Navbar shows up and operates, we just need the content to show
- [x] Landing page needs some responsiveness; middle section goes offscreen in x direction
- [x] Editor should be split horizontally instead of vertically in mobile mode

### PR DESCRIPTION
**Pull request by arashnrim**
This PR will introduce several changes that improve the responsive design of the website on smaller devices. This issue will close #48. Some examples include:

- Improving the `Header` when in the editor — the "Save draft" button has been condensed into another button with a save icon; this is only displayed on smaller devices
- Implementing menu in the `Header` for smaller devices

Additionally, the `Header` component has been heavily refactored to improve code readability.

### CODE REVIEW

**Comment by arashnrim** [comment]
Thanks for the feedback, @AnthonyKuang! I'll follow up on them and work on improving the responsive design even more.

**Comment by AnthonyKuang** [comment]
Keep at it! As you said, patience is a virtue 😇

V/r,
Anthony

**Comment by arashnrim** [comment]
This has been pretty stale for a little while, and it has to do with one issue that I'm not sure I'm able to resolve just yet. I'll create a separate issue regarding it in the meantime, then maybe merge the changes implementing in this PR first.

I'll do this soon, but if you have any other thoughts, let me know!

**Review by NebuDev14 — APPROVED** [review]
Amazing work again Arash!
Everything looks really clean (even the navbar which I had a struggle trying to deal with earlier).

**Comment by IamTregsthedev** [comment]
Congratulations Arash!

You've been working on this on a while. Nice to see this, finally completed

**Pull request merged**
